spring:
  application:
    name: courier-tracking
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:couriertrackingdb
  h2:
    console:
      enabled: true

audit:
  user: system

calculation:
  store-radius: 100
  earth-radius: 6371000